# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
        
      - name: 'Send test email notification'
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          # Required mail server address:
          server_address: smtp-relay.sendinblue.com
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: ${{secrets.SMTP_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.SMTP_PASSWORD}}
          # Required mail subject:
          subject: Test job of ${{github.repository}} started successfully!
          # Required recipients' addresses:
          to: damien.pereira@sysentive.com
          # Required sender full name (address can be skipped):
          from: Tom Dupont
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: false
          # Optional plain body:
          body: Test job of ${{github.repository}} started successfully!
    
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - run: npm ci
      - run: npm test
      
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/mon-app-devops:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mon-app-devops:${{ github.sha }}
      
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ github.ref_name }}-monappdevops
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/mon-app-devops:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
          name: monappdevops-${{ github.ref_name }}
          location: 'francecentral'
      - name: 'Send email notification'
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          # Required mail server address:
          server_address: smtp-relay.sendinblue.com
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: ${{secrets.SMTP_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.SMTP_PASSWORD}}
          # Required mail subject:
          subject: Deploy job of ${{github.repository}} completed successfully!
          # Required recipients' addresses:
          to: damien.pereira@sysentive.com
          # Required sender full name (address can be skipped):
          from: Tom Dupont
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Deploy job of ${{github.repository}} completed successfully!

          
